version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/afe
      - /afe/node_modules
      - public-data:/afe/public
      - tmp-data:/afe/tmp
      - log-data:/afe/log
    environment:
      RAILS_ENV: production
    command: sh scripts/launch.sh
  nginx:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - public-data:/afe/public
      - tmp-data:/afe/tmp
volumes:
  public-data:
  tmp-data:
  log-data:
